In [1]:
import pandas as pd

In [13]:
moex_df = pd.read_csv("./output_files/moex.csv", sep=";").set_index("start_date_time")
moex_df

,FIVE,GAZP,MGNT,MOEX,GMKN,PLZL,SBERP,TATNP
start_date_time,,,,,,,,
2020-01-03,2130.5,259.00,3445.5,107.18,19448.0,7286.0,226.40,734.0
2020-01-06,2119.0,256.55,3416.0,108.03,19588.0,7421.5,225.95,736.3
2020-01-08,2109.0,255.79,3427.0,110.84,19850.0,7468.0,230.38,749.1
2020-01-09,2152.0,254.07,3348.0,111.00,19838.0,7326.0,231.00,769.9
2020-01-10,2202.0,251.90,3319.5,112.99,19878.0,7220.0,232.00,773.5
...,...,...,...,...,...,...,...,...
2022-11-21,1523.0,168.13,4856.0,86.95,14654.0,6428.0,130.35,352.4
2022-11-22,1513.0,168.08,4869.0,87.80,14802.0,6741.5,131.38,353.1
2022-11-23,1533.0,169.15,4879.5,87.68,14752.0,7140.5,131.40,354.2
2022-11-24,1560.5,168.96,4893.0,87.74,14766.0,7068.0,131.36,354.4
2022-11-25,1546.5,169.03,4849.0,87.60,14632.0,7008.0,131.19,355.5

In [9]:
yahoo_df = pd.read_csv("./output_files/yahoo.csv", sep=";").set_index("start_date_time")
yahoo_df

,AMD,KO,CAT,CSCO,FDX,F,GS,INTC,JNJ,LOGI,...,MS,NVDA,^IXIC,PFE,SIE.BE,TCS.IL,UPS,YNDX,RUB=X,EURUSD=X
start_date_time,,,,,,,,,,,,,,,,,,,,,
2020-01-02,49.099998,54.990002,150.529999,48.419998,155.100006,9.42,234.320007,60.840000,145.970001,47.669998,...,52.040001,59.977501,9092.190430,37.134724,118.459999,21.950001,116.790001,44.080002,61.830002,1.122083
2020-01-03,48.599998,54.689999,148.440002,47.630001,153.179993,9.21,231.580002,60.099998,144.279999,47.209999,...,51.200001,59.017502,9020.769531,36.935486,116.320000,21.600000,116.720001,43.209999,61.694199,1.117144
2020-01-06,48.389999,54.669998,148.339996,47.799999,153.300003,9.16,233.949997,59.930000,144.100006,47.180000,...,51.020000,59.264999,9071.469727,36.888046,116.180000,21.549999,116.199997,43.099998,62.029999,1.116196
2020-01-07,48.250000,54.250000,146.380005,47.490002,154.800003,9.25,235.490005,58.930000,144.979996,47.310001,...,50.919998,59.982498,9068.580078,36.764706,116.639999,21.450001,116.000000,43.169998,61.775002,1.119799
2020-01-08,47.830002,54.349998,147.679993,47.520000,157.130005,9.25,237.759995,58.970001,144.960007,47.619999,...,51.570000,60.095001,9129.240234,37.058823,116.379997,22.000000,116.660004,43.770000,61.930901,1.115474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-18,73.570000,61.139999,231.429993,47.790001,174.720001,13.99,379.200012,29.870001,176.199997,58.930000,...,89.199997,154.089996,11146.059570,48.230000,132.259995,9.500000,178.970001,18.940001,60.365002,1.036173
2022-11-21,72.459999,62.080002,232.169998,47.619999,173.639999,13.95,380.209991,28.940001,175.970001,57.849998,...,89.080002,153.169998,11024.509766,48.180000,129.259995,10.250000,180.610001,18.940001,60.814999,1.033090
2022-11-22,75.250000,62.349998,237.259995,48.380001,175.669998,14.07,383.869995,29.820000,176.820007,57.959999,...,89.669998,160.380005,11174.410156,49.080002,129.899994,3.193000,182.740005,18.940001,60.625000,1.024569
2022-11-23,76.400002,62.630001,236.919998,48.570000,176.360001,14.03,386.250000,29.670000,177.009995,58.959999,...,89.930000,165.190002,11285.320312,48.849998,131.059998,3.193000,182.839996,18.940001,60.630001,1.031109
2022-11-25,75.139999,62.689999,235.699997,48.400002,176.699997,14.08,388.859985,29.340000,177.240005,59.080002,...,90.910004,162.699997,11226.360352,49.209999,131.580002,3.193000,182.520004,18.940001,60.330002,1.040810

In [14]:
joined_df = moex_df.join(yahoo_df, how="outer")
joined_df

,FIVE,GAZP,MGNT,MOEX,GMKN,PLZL,SBERP,TATNP,AMD,KO,...,MS,NVDA,^IXIC,PFE,SIE.BE,TCS.IL,UPS,YNDX,RUB=X,EURUSD=X
start_date_time,,,,,,,,,,,,,,,,,,,,,
2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.099998,54.990002,...,52.040001,59.977501,9092.190430,37.134724,118.459999,21.950001,116.790001,44.080002,61.830002,1.122083
2020-01-03,2130.5,259.00,3445.5,107.18,19448.0,7286.0,226.40,734.0,48.599998,54.689999,...,51.200001,59.017502,9020.769531,36.935486,116.320000,21.600000,116.720001,43.209999,61.694199,1.117144
2020-01-06,2119.0,256.55,3416.0,108.03,19588.0,7421.5,225.95,736.3,48.389999,54.669998,...,51.020000,59.264999,9071.469727,36.888046,116.180000,21.549999,116.199997,43.099998,62.029999,1.116196
2020-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.250000,54.250000,...,50.919998,59.982498,9068.580078,36.764706,116.639999,21.450001,116.000000,43.169998,61.775002,1.119799
2020-01-08,2109.0,255.79,3427.0,110.84,19850.0,7468.0,230.38,749.1,47.830002,54.349998,...,51.570000,60.095001,9129.240234,37.058823,116.379997,22.000000,116.660004,43.770000,61.930901,1.115474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-21,1523.0,168.13,4856.0,86.95,14654.0,6428.0,130.35,352.4,72.459999,62.080002,...,89.080002,153.169998,11024.509766,48.180000,129.259995,10.250000,180.610001,18.940001,60.814999,1.033090
2022-11-22,1513.0,168.08,4869.0,87.80,14802.0,6741.5,131.38,353.1,75.250000,62.349998,...,89.669998,160.380005,11174.410156,49.080002,129.899994,3.193000,182.740005,18.940001,60.625000,1.024569
2022-11-23,1533.0,169.15,4879.5,87.68,14752.0,7140.5,131.40,354.2,76.400002,62.630001,...,89.930000,165.190002,11285.320312,48.849998,131.059998,3.193000,182.839996,18.940001,60.630001,1.031109
2022-11-24,1560.5,168.96,4893.0,87.74,14766.0,7068.0,131.36,354.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11-25,1546.5,169.03,4849.0,87.60,14632.0,7008.0,131.19,355.5,75.139999,62.689999,...,90.910004,162.699997,11226.360352,49.209999,131.580002,3.193000,182.520004,18.940001,60.330002,1.040810

In [17]:
joined_df.to_csv("./output_files/joined.csv", sep=";",decimal=",")