In [4]:
import pandas_datareader as pdr
from datetime import date

In [19]:
from_dt = date(2020, 9, 15)
till_dt = date(2020, 9, 18)

In [20]:
data = pdr.get_data_moex(['SBERP'], from_dt, till_dt)
data

/home/vscode/.local/lib/python3.11/site-packages/pandas_datareader/moex.py:215: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append(part)

,ACCINT,ADMITTEDQUOTE,ADMITTEDVALUE,BEICLOSE,BID,BOARDID,BOARDNAME,BUYBACKDATE,CBRCLOSE,CLOSE,...,TRENDWAPPR,TYPE,VALUE,VOLUME,WAPRICE,WAVAL,YIELDATWAP,YIELDCLOSE,YIELDLASTCOUPON,YIELDTOOFFER
TRADEDATE,,,,,,,,,,,,,,,,,,,,,
2020-09-15,NaN,221.54,2.077410e+09,NaN,NaN,TQBR,NaN,NaN,NaN,221.87,...,NaN,NaN,2.169391e+09,9841930.0,220.42,0.0,NaN,NaN,NaN,NaN
2020-09-16,NaN,222.30,1.578153e+09,NaN,NaN,TQBR,NaN,NaN,NaN,222.11,...,NaN,NaN,1.801868e+09,8118170.0,221.95,0.0,NaN,NaN,NaN,NaN
2020-09-17,NaN,222.15,1.533761e+09,NaN,NaN,TQBR,NaN,NaN,NaN,221.89,...,NaN,NaN,1.613217e+09,7287850.0,221.36,0.0,NaN,NaN,NaN,NaN
2020-09-18,NaN,221.78,1.096895e+09,NaN,NaN,TQBR,NaN,NaN,NaN,222.14,...,NaN,NaN,1.232319e+09,5554780.0,221.85,0.0,NaN,NaN,NaN,NaN

In [21]:
pdr.get_data_moex(['AAPL-RM'], from_dt, till_dt)

/home/vscode/.local/lib/python3.11/site-packages/pandas_datareader/moex.py:215: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append(part)

,ACCINT,ADMITTEDQUOTE,ADMITTEDVALUE,BEICLOSE,BID,BOARDID,BOARDNAME,BUYBACKDATE,CBRCLOSE,CLOSE,...,TRENDWAPPR,TYPE,VALUE,VOLUME,WAPRICE,WAVAL,YIELDATWAP,YIELDCLOSE,YIELDLASTCOUPON,YIELDTOOFFER
TRADEDATE,,,,,,,,,,,,,,,,,,,,,
2020-09-15,NaN,8789.0,119691383.0,NaN,NaN,FQBR,NaN,NaN,NaN,8683.0,...,NaN,NaN,194239631.0,22179.0,8758.0,0.0,NaN,NaN,NaN,NaN
2020-09-16,NaN,8529.0,47239396.0,NaN,NaN,FQBR,NaN,NaN,NaN,8482.0,...,NaN,NaN,109320421.0,12769.0,8561.0,0.0,NaN,NaN,NaN,NaN
2020-09-17,NaN,8336.0,68335162.0,NaN,NaN,FQBR,NaN,NaN,NaN,8393.0,...,NaN,NaN,83691004.0,10075.0,8307.0,0.0,NaN,NaN,NaN,NaN
2020-09-18,NaN,8189.0,65901389.0,NaN,NaN,FQBR,NaN,NaN,NaN,8142.0,...,NaN,NaN,89849192.0,10910.0,8235.0,0.0,NaN,NaN,NaN,NaN

In [11]:
data[["OPEN", "LOW","HIGH","CLOSE","VOLUME"]]

              OPEN     LOW    HIGH   CLOSE      VOLUME
TRADEDATE
2020-07-02  37.160  37.160  37.800  37.605  17876400.0
2020-07-03  37.820  37.630  38.255  37.950  13648900.0
2020-07-06  38.005  38.005  38.960  38.560  16565100.0
2020-07-07  38.695  37.915  38.935  38.140  20373700.0

# StockQuoteLoader

In [6]:
from src.moex.moex_stock_quote_loader import MoexStockQuoteLoader, date, TimeFrame
msql = MoexStockQuoteLoader()

In [8]:
from_date = date(2020, 9, 15)
till_date = date(2020, 9, 18)

In [9]:
msql.download("AAPL-RM", from_date, till_date, TimeFrame.D)

/home/vscode/.local/lib/python3.11/site-packages/pandas_datareader/moex.py:215: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  result = result.append(part)

                   open   low  high   close   volume
start_date_time
2020-09-15       8895.0  8537  8921  8683.0  22179.0
2020-09-16       8700.0  8425  8722  8482.0  12769.0
2020-09-17       8600.0  8000  8600  8393.0  10075.0